name: Scheduled Gold Price Tracker

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút để test
  workflow_dispatch:

jobs:
  track-gold-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Gold Price Tracker
        run: dotnet run --project GoldCoreSchedule/GoldCoreSchedule.csproj
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
